apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
      - path: /create_db
        pathType: Prefix
        backend:
          service:
            name: initpy-service
            port:
              number: 5001
      - path: /write_points
        pathType: Prefix
        backend:
          service:
            name: webpy-write-service
            port:
              number: 5003
      - path: /print_points
        pathType: Prefix
        backend:
          service:
            name: webpy-print-service
            port:
              number: 5000
      - path: /gothem/
        pathType: Prefix
        backend:
          service:
            name: multistage-service
            port:
              number: 5002  