apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 8080
      - path: /init
        pathType: Prefix
        backend:
          service:
            name: initpy-service
            port:
              number: 5001
      - path: /web
        pathType: Prefix
        backend:
          service:
            name: webpy-service
            port:
              number: 5000
      - path: /monkeys
        pathType: Prefix
        backend:
          service:
            name: multistage-service
            port:
              number: 5002  